#pragma once

#define REAL_WINDOWS_VERSION 11
#define REAL_WINDOWS_PROCESSOR_VENDER "Intel"
#define REAL_WINDOWS_GRAPHICS_CARD_VENDER "Nvidia"
#define REAL_WINDOWS_CURRENTLY_SUPPORTED_GPUS " 3050"